version: '2'
services:
  web:
    build: ./web
    ports:
     - "5000:5000"
    volumes:
     - ./web:/code
  web2:
    build: ./web2
    ports:
     - "8001:5000"
    volumes:
     - ./web2:/code
  redis:
    image: "redis:alpine"

  web3:
    build: ./web3
    ports:
     - "8008:5000"
    volumes:
     - ./web3:/code
  redis:
    image: "redis:alpine"
