version: '2'
services:
  web:
    build: ./web
    ports:
     - "5000:5000"
    volumes:
     - ./web:/code
  web2:
    build: ./web2
    ports:
     - "127.0.0.1:8001:8001"
    volumes:
     - ./web2:/code
  redis:
    image: "redis:alpine"
